[workspace]
members = [
    "ftd",
    "fastn",
    "fastn-core",
    "fastn-cloud",
    "fastn-package",
    "fastn-issues",
    "fastn-js",
    "fastn-grammar",
    "fastn-lang",
    "foo",
    # "fastn-wasm",
    # "fastn-runtime",
]
exclude = ["fastn-runtime", "fastn-wasm"]
resolver = "2"

[workspace.package]
authors = [
    "Amit Upadhyay <upadhyay@gmail.com>",
    "Arpita Jaiswal <arpita@fifthtry.com>",
    "Sourabh Garg <sourabh@fifthtry.com>",
    "Shobhit Sharma <shobhit@fifthtry.com>",
    "Abrar Khan <abrar@fifthtry.com>",
    "Rithik Seth <rithik@fifthtry.com>",
    "Ganesh Salunke <ganesh@fifthtry.com>",
]
edition = "2021"
description = "fastn: Full-stack Web Development Made Easy"
license = "BSD-3-Clause"
repository = "https://github.com/fastn-stack/fastn"
homepage = "https://fastn.com"

[profile.release]
# enabling this descreased our binary size from 30M to 27M on linux (as of 12th Jun 2023). The build time went up (no
# objective data). Disabling it for now. It made a huge difference in fastn-runtime wasm size (without lto: 2.1M with
# lto: 518K).
#lto = true
strip = true
#opt-level = "z"
#panic = "abort"

[workspace.dependencies]
# Please do not specify a dependency more precisely than needed. If version "1" works, do
# not specify "1.1.42". This reduces the number of total dependencies, as if you specify
# 1.1.42 and someone else who only needed "1" also specified 1.1.37, we end up having same
# dependency getting compiled twice.
#
# In future we may discover that our code does not indeed work with "1", say it ony works
# for 1.1 onwards, or 1.1.25 onwards, in which case use >= 1.1.25 etc. Saying our code
# only works for 1.1.42 and not 1.1.41 nor 1.1.43 is really weird, and most likely wrong.
#
# If you are not using the latest version intentionally, please do not list it in this section
# and create it's own [dependencies.<name>] section, and document it with why are you not
# using the latest dependency, and what is the plan to moving to the latest version.

accept-language = "3"
actix-web = "4"
antidote = "1"
dirs = "5"
native-tls = "0.2"
deadpool-postgres = { git = "https://github.com/amitu/deadpool", rev = "dbf5a46" }
postgres-native-tls = "0.5"
tokio-postgres = { version = "0.7", features = ["with-serde_json-1", "with-uuid-1"] }
postgres-types = "0.2"
async-lock = "3"
async-recursion = "1"
async-trait = "0.1"
actix-web-lab = "0.20"
bitflags = "2"
bytemuck = { version = "1", features = [ "derive" ] }
camino = "1"
clap = "4"
colored = "2"
crossterm = "0.27"
css-color-parser = "0.1"
diffy = "0.3"
dioxus-html = { git = "https://github.com/DioxusLabs/dioxus", rev = "fb52673433cc57a70c86185ffa7da5fa3a2394da" }
dioxus-native-core = { git = "https://github.com/DioxusLabs/dioxus", rev = "fb52673433cc57a70c86185ffa7da5fa3a2394da" }
dioxus-native-core-macro = { git = "https://github.com/DioxusLabs/dioxus", rev = "fb52673433cc57a70c86185ffa7da5fa3a2394da" }
dotenvy = "0.15"
edit = "0.1"
env_logger = "0.10"
enum-iterator = "0.6"
enum-iterator-derive = "0.6"
fastn-cloud = { path = "fastn-cloud" }
fastn-core = { path = "fastn-core" }
fastn-issues = { path = "fastn-issues" }
fastn-package = { path = "fastn-package" }
fastn-runtime = { path = "fastn-runtime" }
fastn-wasm = { path = "fastn-wasm" }
fastn-grammar = { path = "fastn-grammar" }
fluent = "0.16"
format_num = "0.1"
ftd = { path = "ftd" }
fastn-js = { path = "fastn-js" }
futures = "0.3"
futures-util = { version = "0.3", default-features = false, features = ["std"] }
futures-core = "0.3"
home = "0.5"
ignore = "0.4"
include_dir = "0.7"
indoc = "2"
intl-memoizer = "0.5"
itertools = "0.12"
log = "0.4"
magic-crypt = { version = "3", default-features = false }
mime_guess = "2"
oauth2 = { version = "4" }
once_cell = "1"
pretty = "0.12"
pretty_assertions = "1"
rand = "0.8"
rand_pcg = "0.3"
realm-lang = "0.1"
regex = "1"
reqwest = { version = "0.11", features = ["json"] }
rink = { git = "https://github.com/DioxusLabs/dioxus", rev = "fb52673433cc57a70c86185ffa7da5fa3a2394da" }
ron = "0.8"
rquickjs = { version = "0.3", features = ["macro"] }
quick-js = "0.4"
rustc-hash = "1"
rusty-hook = "0.11"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
slotmap = "1"
slug = "0.1"
taffy = "0.3"
tejar = "0.1"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
url = "2"
ansi_term = "0.12"
walkdir = "2"
smallvec = "1"
wasm-bindgen = "0.2"
wasmtime = "15"
wgpu = "0.18"
winit = "0.29"
zip = "0.6"
prettify-js = "0.1.0"
indexmap = { version = "2", features = ["serde"] }
argon2 = "0.5"
lettre = { version = "0.11", features = ["serde", "tokio1", "tokio1-native-tls"]}
diesel = { version = "2.1", features = ["chrono", "postgres", "postgres_backend"]}
diesel-async = { version = "0.4", features = ["postgres", "deadpool", "async-connection-wrapper"]}
diesel_migrations = "2.1"
chrono = { version = "0.4", features = ["serde"]}

[workspace.dependencies.uuid]
version = "1.6.1"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
    "serde",
]

[workspace.dependencies.fastn-observer]
git = "https://github.com/fastn-stack/fastn-observer"
rev = "47b29ea"

[workspace.dependencies.rusqlite]
version = "0.30"
features = [
    # We are using bundled version of rusqlite so we do not need sqlitelib, headers as a
    # dependency. By default, if we do not bundle, our binary will link against system
    # provided sqlite, which would have been a good thing, if we used system sqlite, our
    # binary size would be smaller, compile time lesser, but unfortunately we can not assume
    # sqlite dynamic library is installed on everyone's machine. We can chose to give two
    # binaries, one with bundled, one without, but it is not worth the tradeoff right now.
    "bundled",
    "column_decltype",
]


[workspace.dependencies.web-sys]
version = "0.3"
features = [
    'Document',
    'Element',
    'HtmlElement',
    'Node',
    'Window',
]

[workspace.dependencies.hyper]
version = "1"
default-features = false
features = ["http1", "server"]

[workspace.dependencies.notify]
# Read the following why we disable the default feature:
# https://docs.rs/notify/5.0.0/notify/index.html#crossbeam-channel--tokio
version = "6"
default-features = false
features=["macos_kqueue"]

[workspace.dependencies.fbt-lib]
git = "https://github.com/FifthTry/fbt"
rev = "ea0ee98"

[workspace.dependencies.syntect]
# We use syntect for syntax highlighting feature in ftd.code.
version = "5"

# By default syntect uses https://docs.rs/onig/. Rust has two popular regular expression
# crates, `regex` and `onig`. `onig` is a wrapper over a library implemented in C:
# https://github.com/kkos/oniguruma. https://docs.rs/regex/ is a pure Rust implementation.
#
# We are using `regex` ourselves. `comrak` also uses `regex`. So we disable their default
# feature (which brought in onig), and use `default-fancy`, which uses `fancy-regex`, which
# in turn uses `regex`.
default-features = false
features = [
    # TODO: This feature brings in a lot of feaures, we have to pare it down to exactly
    #       the features we need.
    "default-fancy"
]

[workspace.dependencies.comrak]
# We use comrak for markup processing.

version = "0.19"
# By default comrak ships with support for syntax highlighting using syntext for "fenced
# code blocks". We have disabled that by not using default features. We did that because
# we already have a way to show code in ftd, ftd.code. Further, comark requires syntect 4.6
# and we are using 5, which means we have two sytnax highlighting libraries.
#
# Further, in future we have to manipulate the markup at AST level, instead of using the
# to_string() interface. https://fpm.dev/journal/#markdown-styling. So in the meanwhile
# we are disabling their conflicting syntect implementation.
default-features = false
