blank_issues_enabled: false
contact_links:
  - name: fastn Discord
    url: https://discord.gg/fwhk5m3AMG
    about: fastn developer discussion and community chat
  - name: Feature Requests and Ideas
    url: https://github.com/orgs/fastn-stack/discussions/categories/ideas-rfcs
    about: Create a Discussion instead of issue for ideas and proposals
