[package]
name = "fastn"
version = "0.4.31"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
clap.workspace = true
colored.workspace = true
fastn-cloud.workspace = true
fastn-observer.workspace = true
fastn-core.workspace = true
futures.workspace = true
reqwest.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
dotenvy.workspace = true


[features]
remote = ["fastn-core/remote"]
