[package]
name = "fastn-issues"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
ftd.workspace = true
rusqlite.workspace = true
thiserror.workspace = true
