name: Cue Checks

on:
  workflow_dispatch:
jobs:
  everything:
    name: Rust Checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
      - name: Run cue test
        run: bash .github/cue.sh
