name: Integration Testing

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  integration-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          components: rustfmt, clippy

      - name: Fastn install
        id: fastn-install
        continue-on-error: true
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --path fastn --profile dev

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask
          pip install psycopg2

      - name: Wait for PostgreSQL to start
        run: |
          timeout=30
          until pg_isready -h localhost -p 5432 -U testuser -d testdb || ((timeout-- <= 0)); do
            sleep 1
          done

      - name: Current Directory
        run: |
          echo "Current Working Directory"
          pwd 
          echo "Current Directory files"
          ls -al 

      - name: Populate sample data
        run: |
          python scripts/populate-table.py

      - name: Test Hello World
        run: |
          python scripts/hello-world-test.py

      - name: Test server (port 5000)
        run: |
          python scripts/test-server.py

      - name: Current Directory (before testing)
        run: |
          echo "Current Working Directory"
          pwd 
          echo "Current Directory files"
          ls -al 

      - name: Run integration tests (hello world)
        run: |
          cd integration-tests/01-hello-world
          fastn test --headless
